### ISSUE TITLE
Quizzes multiple choice error

### ISSUE THREAD

**Issue by SophiaFedder98** [prolog-hhu/website#24]
While creating multiple choice tasks and thier corresponding possible answers, two errors occure when trying to publish the quizz. First error states that the false answers have to be marked correct in order to compile although the correct answer is already included. Second error states that to every answer the feedback field needs to be filled eventhough it is unnecessary to give a feedback to the right answers in my opinion.

**Comment by smnmnkr** [comment]
Fixed. The latest update of a WordPress submodule introduced a bug, which marked these two fields as required. 
Important is, that within a regular expression special characters like brackets and punctuation marks must be escaped (\(, \.).
A great place to test these rather than our system is the following platform: https://regex101.com/
